import type { InterviewQuestion, InterviewCategory, InterviewDifficulty } from "./types";

export const interviewQuestions: InterviewQuestion[] = [
  {
    id: "se-beginner-1",
    category: "Software Engineering",
    difficulty: "Beginner",
    question: "What is the difference between the frontend and backend of a web application?",
    importantKeywords: [
      "frontend",
      "backend",
      "client",
      "server",
      "API",
      "database",
      "user interface",
    ],
    sampleAnswerPoints: [
      "The frontend handles the user interface and interactions in the browser or app.",
      "The backend contains business logic, APIs, and data access on the server.",
      "The frontend and backend communicate through requests and responses, often using APIs.",
    ],
  },
  {
    id: "se-beginner-2",
    category: "Software Engineering",
    difficulty: "Beginner",
    question: "What happens behind the scenes when you enter a website URL into the browser?",
    importantKeywords: ["DNS", "HTTP request", "server", "HTML", "CSS", "JavaScript", "render"],
    sampleAnswerPoints: [
      "The browser resolves the domain name using DNS.",
      "It sends an HTTP or HTTPS request to the server and receives page assets.",
      "The browser parses HTML, CSS, and JavaScript, then renders the page.",
    ],
  },
  {
    id: "se-intermediate-1",
    category: "Software Engineering",
    difficulty: "Intermediate",
    question: "How would you design a simple URL shortener service like bit.ly?",
    importantKeywords: [
      "unique ID",
      "database",
      "redirect",
      "collision",
      "hashing",
      "scalability",
      "analytics",
    ],
    sampleAnswerPoints: [
      "Generate a unique short code for each long URL.",
      "Store the short-to-long URL mapping in a database for fast lookup.",
      "Handle redirects efficiently and plan for collisions, scale, and optional analytics.",
    ],
  },
  {
    id: "se-intermediate-2",
    category: "Software Engineering",
    difficulty: "Intermediate",
    question: "How would you investigate and fix a slow API endpoint in production?",
    importantKeywords: [
      "logs",
      "monitoring",
      "latency",
      "database query",
      "profiling",
      "caching",
      "bottleneck",
    ],
    sampleAnswerPoints: [
      "Measure the problem first with logs, metrics, and traces.",
      "Check whether the bottleneck is in the database, external calls, or application code.",
      "Fix the root cause with targeted changes such as indexing, caching, or code optimization.",
    ],
  },
  {
    id: "se-advanced-1",
    category: "Software Engineering",
    difficulty: "Advanced",
    question: "Design a notification system that supports email and in-app alerts.",
    importantKeywords: [
      "event queue",
      "worker",
      "retry",
      "preferences",
      "idempotent",
      "delivery status",
      "scalability",
    ],
    sampleAnswerPoints: [
      "Use an asynchronous event-driven design so producers are decoupled from delivery.",
      "Workers should send notifications per channel, retry safely, and remain idempotent.",
      "Store user preferences and delivery status so the system can scale and be observed.",
    ],
  },
  {
    id: "se-advanced-2",
    category: "Software Engineering",
    difficulty: "Advanced",
    question:
      "When would you choose eventual consistency instead of strong consistency in a distributed system?",
    importantKeywords: [
      "availability",
      "latency",
      "replication",
      "stale data",
      "trade-off",
      "distributed system",
      "critical transaction",
    ],
    sampleAnswerPoints: [
      "Eventual consistency can improve availability and latency in distributed systems.",
      "It is acceptable when short-lived stale data is okay for the user or business flow.",
      "Strong consistency is still needed for critical transactions or correctness-sensitive data.",
    ],
  },
  {
    id: "ds-beginner-1",
    category: "Data Structures",
    difficulty: "Beginner",
    question: "What is the difference between a stack and a queue?",
    importantKeywords: ["LIFO", "FIFO", "push", "pop", "enqueue", "dequeue", "undo"],
    sampleAnswerPoints: [
      "A stack follows LIFO order, so the last item added is the first removed.",
      "A queue follows FIFO order, so the first item added is the first removed.",
      "Common examples include undo history for stacks and task scheduling for queues.",
    ],
  },
  {
    id: "ds-beginner-2",
    category: "Data Structures",
    difficulty: "Beginner",
    question: "How does binary search work, and when can you use it?",
    importantKeywords: [
      "sorted array",
      "middle",
      "halve",
      "comparison",
      "O(log n)",
      "search space",
    ],
    sampleAnswerPoints: [
      "Binary search only works on sorted data.",
      "It compares the target with the middle element and eliminates half the search space each step.",
      "That repeated halving gives binary search logarithmic time complexity.",
    ],
  },
  {
    id: "ds-intermediate-1",
    category: "Data Structures",
    difficulty: "Intermediate",
    question: "When would you use a hash table instead of a tree-based map?",
    importantKeywords: ["O(1)", "ordering", "collision", "lookup", "range query", "trade-off"],
    sampleAnswerPoints: [
      "Hash tables are usually preferred for very fast average-case lookups.",
      "Tree-based maps are better when key ordering, sorted traversal, or range queries matter.",
      "The trade-off includes collisions for hash tables and higher lookup cost for trees.",
    ],
  },
  {
    id: "ds-intermediate-2",
    category: "Data Structures",
    difficulty: "Intermediate",
    question: "Explain the difference between BFS and DFS and when you would choose each.",
    importantKeywords: [
      "queue",
      "stack",
      "recursion",
      "shortest path",
      "graph traversal",
      "backtracking",
    ],
    sampleAnswerPoints: [
      "BFS explores level by level and is commonly implemented with a queue.",
      "DFS explores depth first using a stack or recursion.",
      "BFS is useful for shortest path in unweighted graphs, while DFS is useful for traversal and backtracking.",
    ],
  },
  {
    id: "ds-advanced-1",
    category: "Data Structures",
    difficulty: "Advanced",
    question: "How does an LRU cache work?",
    importantKeywords: [
      "hash map",
      "doubly linked list",
      "O(1)",
      "eviction",
      "recent usage",
      "cache",
    ],
    sampleAnswerPoints: [
      "A hash map provides O(1) access to cached entries.",
      "A doubly linked list tracks which entries were used most and least recently.",
      "On access, entries move to the front, and the least recently used item is evicted from the tail.",
    ],
  },
  {
    id: "ds-advanced-2",
    category: "Data Structures",
    difficulty: "Advanced",
    question: "How would you find the top K most frequent items in a large dataset?",
    importantKeywords: ["frequency map", "heap", "min heap", "top K", "streaming", "complexity"],
    sampleAnswerPoints: [
      "Count item frequencies with a hash map or streaming counter.",
      "Use a min heap of size K to keep only the top K elements efficiently.",
      "Discuss time and memory trade-offs, especially if the dataset is very large or streamed.",
    ],
  },
  {
    id: "web-beginner-1",
    category: "Web Development",
    difficulty: "Beginner",
    question: "What is semantic HTML, and why does it matter?",
    importantKeywords: ["header", "nav", "main", "article", "accessibility", "SEO", "structure"],
    sampleAnswerPoints: [
      "Semantic HTML uses elements that describe meaning and page structure.",
      "It helps accessibility tools and search engines understand the content better.",
      "It also makes code easier to maintain and reason about.",
    ],
  },
  {
    id: "web-beginner-2",
    category: "Web Development",
    difficulty: "Beginner",
    question: "What is the difference between a GET request and a POST request?",
    importantKeywords: ["GET", "POST", "retrieve", "body", "URL", "idempotent", "side effects"],
    sampleAnswerPoints: [
      "GET is commonly used to retrieve data and usually should not change server state.",
      "POST is used to send data, often in the request body, and may create or change data.",
      "GET requests are typically idempotent, while POST requests often have side effects.",
    ],
  },
  {
    id: "web-intermediate-1",
    category: "Web Development",
    difficulty: "Intermediate",
    question: "Explain the difference between React props and React state.",
    importantKeywords: ["props", "parent", "state", "local", "read-only", "re-render", "component"],
    sampleAnswerPoints: [
      "Props are passed into a component, usually from a parent, and are treated as read-only.",
      "State is local data owned by a component and can change over time.",
      "Changes to props or state can trigger a re-render of the component tree.",
    ],
  },
  {
    id: "web-intermediate-2",
    category: "Web Development",
    difficulty: "Intermediate",
    question: "What causes a CORS error, and how do you fix it?",
    importantKeywords: [
      "origin",
      "browser",
      "Access-Control-Allow-Origin",
      "preflight",
      "server headers",
      "proxy",
    ],
    sampleAnswerPoints: [
      "CORS errors happen when the browser blocks a cross-origin request without the right permissions.",
      "The server must return the correct CORS headers for allowed origins, methods, and headers.",
      "In development, a proxy can also help route requests through the same origin.",
    ],
  },
  {
    id: "web-advanced-1",
    category: "Web Development",
    difficulty: "Advanced",
    question: "Compare CSR, SSR, and SSG for a content-heavy site.",
    importantKeywords: [
      "client-side rendering",
      "server-side rendering",
      "static generation",
      "SEO",
      "hydration",
      "performance",
      "caching",
    ],
    sampleAnswerPoints: [
      "CSR renders mostly in the browser and can increase first-load work for the client.",
      "SSR improves initial content delivery and SEO for dynamic pages but adds server complexity.",
      "SSG works well for stable content because pages can be prebuilt, cached, and served quickly.",
    ],
  },
  {
    id: "web-advanced-2",
    category: "Web Development",
    difficulty: "Advanced",
    question: "How would you improve the performance of a slow frontend application?",
    importantKeywords: [
      "profiling",
      "bundle splitting",
      "lazy loading",
      "image optimization",
      "network waterfall",
      "re-render",
      "caching",
    ],
    sampleAnswerPoints: [
      "Start by measuring the problem with profiling tools, browser performance tools, or Web Vitals.",
      "Reduce the initial load with code splitting, lazy loading, and optimized images or assets.",
      "Find unnecessary renders, expensive network requests, or missing caching and fix them systematically.",
    ],
  },
  {
    id: "hr-beginner-1",
    category: "HR Interview",
    difficulty: "Beginner",
    question: "Tell me about yourself.",
    importantKeywords: ["present", "past", "future", "skills", "experience", "role", "concise"],
    sampleAnswerPoints: [
      "Start with your current role, studies, or focus area.",
      "Mention a few relevant past experiences or strengths that connect to the role.",
      "Finish with why this opportunity is the right next step for you.",
    ],
  },
  {
    id: "hr-beginner-2",
    category: "HR Interview",
    difficulty: "Beginner",
    question: "Why do you want this role?",
    importantKeywords: [
      "company",
      "mission",
      "skills",
      "growth",
      "impact",
      "alignment",
      "research",
    ],
    sampleAnswerPoints: [
      "Show that you understand the role and the company or team mission.",
      "Connect your relevant skills or experience to what the role needs.",
      "Explain the impact you want to make and the kind of growth you are looking for.",
    ],
  },
  {
    id: "hr-intermediate-1",
    category: "HR Interview",
    difficulty: "Intermediate",
    question: "Describe a time you had a disagreement with a teammate.",
    importantKeywords: [
      "STAR",
      "communication",
      "listen",
      "compromise",
      "outcome",
      "respect",
      "resolution",
    ],
    sampleAnswerPoints: [
      "Use a clear situation and task so the interviewer understands the context.",
      "Explain how you listened, communicated calmly, and worked toward a practical resolution.",
      "Finish with the outcome and what you learned from the disagreement.",
    ],
  },
  {
    id: "hr-intermediate-2",
    category: "HR Interview",
    difficulty: "Intermediate",
    question: "Tell me about a failure or mistake and what you learned from it.",
    importantKeywords: [
      "accountability",
      "ownership",
      "lesson",
      "improvement",
      "reflection",
      "result",
    ],
    sampleAnswerPoints: [
      "Choose a real example and explain it honestly without blaming others.",
      "Take ownership of what went wrong and what you would do differently now.",
      "Show the concrete change or improvement that came from the lesson.",
    ],
  },
  {
    id: "hr-advanced-1",
    category: "HR Interview",
    difficulty: "Advanced",
    question: "Tell me about a time you led without formal authority.",
    importantKeywords: [
      "influence",
      "alignment",
      "stakeholders",
      "initiative",
      "communication",
      "result",
      "ownership",
    ],
    sampleAnswerPoints: [
      "Explain the problem or opportunity you recognized before acting.",
      "Show how you influenced teammates or stakeholders through communication and alignment instead of authority.",
      "Describe the measurable result and why the effort mattered.",
    ],
  },
  {
    id: "hr-advanced-2",
    category: "HR Interview",
    difficulty: "Advanced",
    question: "Describe how you handled an ambiguous problem with limited direction.",
    importantKeywords: [
      "clarify",
      "assumptions",
      "prioritize",
      "experiment",
      "feedback",
      "decision-making",
      "iteration",
    ],
    sampleAnswerPoints: [
      "Break the ambiguous problem into smaller questions or decisions.",
      "State how you validated assumptions with data, experiments, or stakeholder feedback.",
      "Explain how you prioritized actions, made decisions, and adjusted as you learned more.",
    ],
  },
];

export function getInterviewQuestions(
  category: InterviewCategory,
  difficulty: InterviewDifficulty,
) {
  return interviewQuestions.filter(
    (question) => question.category === category && question.difficulty === difficulty,
  );
}

export function getInterviewQuestionById(id: string) {
  return interviewQuestions.find((question) => question.id === id) ?? null;
}
