/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsResumeBuilderRouteImport } from './routes/tools.resume-builder'
import { Route as ToolsResumeAtsRouteImport } from './routes/tools.resume-ats'
import { Route as ToolsReadmeGeneratorRouteImport } from './routes/tools.readme-generator'
import { Route as ToolsPdfToolsRouteImport } from './routes/tools.pdf-tools'
import { Route as ToolsNotesSummarizerRouteImport } from './routes/tools.notes-summarizer'
import { Route as ToolsJsonFormatterRouteImport } from './routes/tools.json-formatter'
import { Route as ToolsGradePredictorRouteImport } from './routes/tools.grade-predictor'
import { Route as ToolsCgpaCalculatorRouteImport } from './routes/tools.cgpa-calculator'
import { Route as ToolsAttendanceCalculatorRouteImport } from './routes/tools.attendance-calculator'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsResumeBuilderRoute = ToolsResumeBuilderRouteImport.update({
  id: '/tools/resume-builder',
  path: '/tools/resume-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsResumeAtsRoute = ToolsResumeAtsRouteImport.update({
  id: '/tools/resume-ats',
  path: '/tools/resume-ats',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsReadmeGeneratorRoute = ToolsReadmeGeneratorRouteImport.update({
  id: '/tools/readme-generator',
  path: '/tools/readme-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPdfToolsRoute = ToolsPdfToolsRouteImport.update({
  id: '/tools/pdf-tools',
  path: '/tools/pdf-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsNotesSummarizerRoute = ToolsNotesSummarizerRouteImport.update({
  id: '/tools/notes-summarizer',
  path: '/tools/notes-summarizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJsonFormatterRoute = ToolsJsonFormatterRouteImport.update({
  id: '/tools/json-formatter',
  path: '/tools/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsGradePredictorRoute = ToolsGradePredictorRouteImport.update({
  id: '/tools/grade-predictor',
  path: '/tools/grade-predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCgpaCalculatorRoute = ToolsCgpaCalculatorRouteImport.update({
  id: '/tools/cgpa-calculator',
  path: '/tools/cgpa-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAttendanceCalculatorRoute =
  ToolsAttendanceCalculatorRouteImport.update({
    id: '/tools/attendance-calculator',
    path: '/tools/attendance-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools/attendance-calculator': typeof ToolsAttendanceCalculatorRoute
  '/tools/cgpa-calculator': typeof ToolsCgpaCalculatorRoute
  '/tools/grade-predictor': typeof ToolsGradePredictorRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/notes-summarizer': typeof ToolsNotesSummarizerRoute
  '/tools/pdf-tools': typeof ToolsPdfToolsRoute
  '/tools/readme-generator': typeof ToolsReadmeGeneratorRoute
  '/tools/resume-ats': typeof ToolsResumeAtsRoute
  '/tools/resume-builder': typeof ToolsResumeBuilderRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools/attendance-calculator': typeof ToolsAttendanceCalculatorRoute
  '/tools/cgpa-calculator': typeof ToolsCgpaCalculatorRoute
  '/tools/grade-predictor': typeof ToolsGradePredictorRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/notes-summarizer': typeof ToolsNotesSummarizerRoute
  '/tools/pdf-tools': typeof ToolsPdfToolsRoute
  '/tools/readme-generator': typeof ToolsReadmeGeneratorRoute
  '/tools/resume-ats': typeof ToolsResumeAtsRoute
  '/tools/resume-builder': typeof ToolsResumeBuilderRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tools/attendance-calculator': typeof ToolsAttendanceCalculatorRoute
  '/tools/cgpa-calculator': typeof ToolsCgpaCalculatorRoute
  '/tools/grade-predictor': typeof ToolsGradePredictorRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/notes-summarizer': typeof ToolsNotesSummarizerRoute
  '/tools/pdf-tools': typeof ToolsPdfToolsRoute
  '/tools/readme-generator': typeof ToolsReadmeGeneratorRoute
  '/tools/resume-ats': typeof ToolsResumeAtsRoute
  '/tools/resume-builder': typeof ToolsResumeBuilderRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/tools/attendance-calculator'
    | '/tools/cgpa-calculator'
    | '/tools/grade-predictor'
    | '/tools/json-formatter'
    | '/tools/notes-summarizer'
    | '/tools/pdf-tools'
    | '/tools/readme-generator'
    | '/tools/resume-ats'
    | '/tools/resume-builder'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/tools/attendance-calculator'
    | '/tools/cgpa-calculator'
    | '/tools/grade-predictor'
    | '/tools/json-formatter'
    | '/tools/notes-summarizer'
    | '/tools/pdf-tools'
    | '/tools/readme-generator'
    | '/tools/resume-ats'
    | '/tools/resume-builder'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/tools/attendance-calculator'
    | '/tools/cgpa-calculator'
    | '/tools/grade-predictor'
    | '/tools/json-formatter'
    | '/tools/notes-summarizer'
    | '/tools/pdf-tools'
    | '/tools/readme-generator'
    | '/tools/resume-ats'
    | '/tools/resume-builder'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ToolsAttendanceCalculatorRoute: typeof ToolsAttendanceCalculatorRoute
  ToolsCgpaCalculatorRoute: typeof ToolsCgpaCalculatorRoute
  ToolsGradePredictorRoute: typeof ToolsGradePredictorRoute
  ToolsJsonFormatterRoute: typeof ToolsJsonFormatterRoute
  ToolsNotesSummarizerRoute: typeof ToolsNotesSummarizerRoute
  ToolsPdfToolsRoute: typeof ToolsPdfToolsRoute
  ToolsReadmeGeneratorRoute: typeof ToolsReadmeGeneratorRoute
  ToolsResumeAtsRoute: typeof ToolsResumeAtsRoute
  ToolsResumeBuilderRoute: typeof ToolsResumeBuilderRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/resume-builder': {
      id: '/tools/resume-builder'
      path: '/tools/resume-builder'
      fullPath: '/tools/resume-builder'
      preLoaderRoute: typeof ToolsResumeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/resume-ats': {
      id: '/tools/resume-ats'
      path: '/tools/resume-ats'
      fullPath: '/tools/resume-ats'
      preLoaderRoute: typeof ToolsResumeAtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/readme-generator': {
      id: '/tools/readme-generator'
      path: '/tools/readme-generator'
      fullPath: '/tools/readme-generator'
      preLoaderRoute: typeof ToolsReadmeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/pdf-tools': {
      id: '/tools/pdf-tools'
      path: '/tools/pdf-tools'
      fullPath: '/tools/pdf-tools'
      preLoaderRoute: typeof ToolsPdfToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/notes-summarizer': {
      id: '/tools/notes-summarizer'
      path: '/tools/notes-summarizer'
      fullPath: '/tools/notes-summarizer'
      preLoaderRoute: typeof ToolsNotesSummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/json-formatter': {
      id: '/tools/json-formatter'
      path: '/tools/json-formatter'
      fullPath: '/tools/json-formatter'
      preLoaderRoute: typeof ToolsJsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/grade-predictor': {
      id: '/tools/grade-predictor'
      path: '/tools/grade-predictor'
      fullPath: '/tools/grade-predictor'
      preLoaderRoute: typeof ToolsGradePredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cgpa-calculator': {
      id: '/tools/cgpa-calculator'
      path: '/tools/cgpa-calculator'
      fullPath: '/tools/cgpa-calculator'
      preLoaderRoute: typeof ToolsCgpaCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/attendance-calculator': {
      id: '/tools/attendance-calculator'
      path: '/tools/attendance-calculator'
      fullPath: '/tools/attendance-calculator'
      preLoaderRoute: typeof ToolsAttendanceCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ToolsAttendanceCalculatorRoute: ToolsAttendanceCalculatorRoute,
  ToolsCgpaCalculatorRoute: ToolsCgpaCalculatorRoute,
  ToolsGradePredictorRoute: ToolsGradePredictorRoute,
  ToolsJsonFormatterRoute: ToolsJsonFormatterRoute,
  ToolsNotesSummarizerRoute: ToolsNotesSummarizerRoute,
  ToolsPdfToolsRoute: ToolsPdfToolsRoute,
  ToolsReadmeGeneratorRoute: ToolsReadmeGeneratorRoute,
  ToolsResumeAtsRoute: ToolsResumeAtsRoute,
  ToolsResumeBuilderRoute: ToolsResumeBuilderRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
